export const SELECT_COFFEE_OPTION = "SELECT_COFFEE_OPTION";
export const SELECT_COFFEE_TYPE = "SELECT_COFFEE_TYPE";
export const SELECT_MILK_TYPE = "SELECT_MILK_TYPE";
export const GO_TO_PREVIOUS_STEP = "GO_TO_PREVIOUS_STEP";
export const GO_TO_NEXT_STEP = "GO_TO_NEXT_STEP";
export const GO_TO_FIRST_STEP = "GO_TO_FIRST_STEP";
